[shell]
program = "/opt/homebrew/bin/fish"
args = ["--login", "-c", "tmux a -t main || tmux new -s main"]

[env]
TERM = "xterm-256color"

[window]
dimensions = { columns = 140, lines = 35 }
position = { x = 300, y = 220 }
padding = { x = 2, y = 2 }
decorations = "None"
startup_mode = "Maximized"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 15

[cursor]
vi_mode_style = "None"
