[symlinks]
"hypr" = ".config/hypr"
"waybar" = ".config/waybar"
"rofi" = ".config/rofi"
"yazi" = ".config/yazi"
"satty" = ".config/satty"

"alacritty" = ".config/alacritty"
"zellij" = ".config/zellij"
"wezterm" = ".config/wezterm"

"zed" = ".config/zed"
"nvim" = ".config/nvim"

"lazygit" = ".config/lazygit"
"mise" = ".config/mise"

"fish/config.fish" = ".config/fish/config.fish"
"fish/functions" = ".config/fish/functions"

"git/.gitconfig" = ".gitconfig"
"npm/.npmrc" = ".npmrc"

[packages]
ignored = [
	"base", "base-devel", "linux", "linux-firmware", "efibootmgr",
	"btrfs-progs", "zram-generator",
	"bluez", "bluez-utils", "networkmanager", "libpulse",
	"pipewire", "pipewire-alsa", "pipewire-jack", "pipewire-pulse", "gst-plugin-pipewire", "wireplumber",
	"paru", "paru-debug", "symm"
]

fonts = ["noto-fonts", "noto-fonts-cjk", "noto-fonts-emoji", "ttf-jetbrains-mono-nerd"]

apps = ["firefox", "google-chrome", "obs-studio", "telegram-desktop", "blender"]

amd = ["amd-ucode", "vulkan-radeon", "vulkan-tools"]

terminal = [
  "alacritty", "zellij", "neovim", "fish", "starship", "fastfetch",
	"tabiew", "btop",
	"yazi", "ueberzugpp", "resvg",
  "fzf", "jq", "ripgrep", "zoxide", "eza", "fd", "bat", "unzip",
  "git", "git-delta", "lazygit",
  "openbsd-netcat", "openssh", "rsync", "bind", "cmake", "postgresql",
	"docker", "docker-buildx", "docker-compose", "lazydocker",
	"kubectl", "helm", "k9s", "doctl", "glab", "ansible", "opentofu", "fluxcd"
]

desktop_hyprland = [
	"uwsm", "hyprland", "hyprpaper", "hyprlock",
	"xdg-desktop-portal-hyprland", "xdg-desktop-portal-gtk",
	"brightnessctl", "waybar", "swaync", "rofi", "nwg-look", "power-profiles-daemon",
	"dolphin", "pavucontrol", "7zip", "mpv", "clipse", "bluetui", "satty", "grim", "slurp",
	"papirus-icon-theme", "apple_cursor"
]
