[symlinks]
"hypr" = ".config/hypr"
"waybar" = ".config/waybar"

"ghostty" = ".config/ghostty"
"wezterm" = ".config/wezterm"

"zed" = ".config/zed"
"nvim" = ".config/nvim"

"lazygit" = ".config/lazygit"
"mise" = ".config/mise"

"fish/config.fish" = ".config/fish/config.fish"
"git/.gitconfig" = ".gitconfig"
"npm/.npmrc" = ".npmrc"
