---
# Global variables for Arch Linux setup

# User configuration
default_shell: /usr/bin/fish

# Dotfiles configuration
dotfiles_repo: ""  # Set this to your dotfiles repository URL
dotfiles_dir: "{{ ansible_env.HOME }}/dotfiles"

# Package lists
base_packages:
  - base-devel
  - git
  - curl
  - wget
  - fish
  - neovim

development_packages:
  - fzf
  - ripgrep
  - fd
  - bat
  - git-delta
  - lazygit
  - lazydocker
  - btop
  - openbsd-netcat
  - rsync
  - wezterm

kde_packages:
  - plasma-desktop
  - plasma-pa
  - plasma-nm
  - plasma-firewall
  - kscreen
  - bluedevil
  - powerdevil
  - power-profiles-daemon
  - dolphin
  - ark
  - spectacle

hyprland_packages:
  - hyprland
  - uwsm
  - libnewt
  - waybar
  - rofi-wayland

nvidia_packages:
  - nvidia
  - nvidia-utils
  - lib32-nvidia-utils

# Feature flags
install_kde: true
install_hyprland: false  # Set to true if you want Hyprland
install_nvidia: false    # Set to true if you have NVIDIA GPU
install_yay: true
enable_multilib: true
disable_kwallet: true

# Rust configuration
rust_toolchain: stable

# AUR helper
aur_helper: yay
aur_helper_repo: https://aur.archlinux.org/yay.git

# Service configuration
enable_sddm: true
enable_networkmanager: true

# Dotfiles symlink configuration (matches your dotfiles.toml)
dotfiles_symlinks:
  wezterm: ".config/wezterm"
  zed: ".config/zed"
  nvim: ".config/nvim"
  lazygit: ".config/lazygit"
  mise: ".config/mise"
  fish_config: ".config/fish/config.fish"
  gitconfig: ".gitconfig"
  npmrc: ".npmrc"
