[window]
dimensions = { columns = 130, lines = 30 }
position = { x = 500, y = 350 }

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 14
offset.y = 4

[cursor]
vi_mode_style = "None"
